### ISSUE TITLE
how to set flexDirection of each section to row?

### ISSUE THREAD

**Issue by ddikodroid** [Kieran-McIntyre/react-native-section-alphabet-list#10]
I want to implement like in the picture below
![section list](https://user-images.githubusercontent.com/4207774/111393764-fae9e080-86eb-11eb-805f-2014b7fccbc4.PNG)

But I can't figure it out how to set flexDirection to row.
Thanks in advance.

**Comment by Kieran-McIntyre** [comment]
> I want to implement like in the picture below
> ![section list](https://user-images.githubusercontent.com/4207774/111393764-fae9e080-86eb-11eb-805f-2014b7fccbc4.PNG)
> 
> But I can't figure it out how to set flexDirection to row.
> Thanks in advance.

Hey @ddikodroid. Currently, `react-native-section-alphabet-list` makes use of a single `SectionList` to render the items. But with your example, we essentially have a horizontal `FlatList` inside a vertical `SectionList`. So maybe an approach you could take would be something like this:

```javascript
<AlphabetList
    data={...}
    // Return null since we want to render the items with the FlatList, not with this SectionList
    renderCustomItem={() => null}
    renderCustomSectionHeader={(section) => {
       return {
           <View>
                <Text>{section.title}</Text>
                <FlatList
                    horizontal
                    data={section.data}
                    renderItem={(item) => <View>My Item Here</View>}
                />
           </View>
       }
    }}
/>
```

You may have to do some additional tweaking, but let me know if this works for you. Thanks.

**Comment by ddikodroid** [comment]
@Kieran-McIntyre one more question, how to give styling to the alphabet index?

**Comment by Kieran-McIntyre** [comment]
> @Kieran-McIntyre one more question, how to give styling to the alphabet index?

@ddikodroid Currently you can only change the color of the alphabet index using the `indexLetterColor` prop. However, the feature to change the style of the index fully is something that has been on the radar for a while.
