### ISSUE TITLE
Custom component for indexLetterList

### ISSUE THREAD

**Issue by nickvdwaal** [Kieran-McIntyre/react-native-section-alphabet-list#11]
Hey! 

I am enjoying your package thus far, the only problem/limitation I am currently facing is the ability to customize the indexLetterList with a custom component or custom styling. Do you have any solution for this?

**Comment by Kieran-McIntyre** [comment]
> Hey!
> 
> I am enjoying your package thus far, the only problem/limitation I am currently facing is the ability to customize the indexLetterList with a custom component or custom styling. Do you have any solution for this?

Hey @nickvdwaal ,

Glad you're enjoying it! This is something that has been [requested previously](https://github.com/Kieran-McIntyre/react-native-section-alphabet-list/issues/10#issuecomment-802219915) and it's something that is currently being worked on. You will be able to set the style of the individual letter index items with the prop `indexLetterStyle`, or if you prefer, render your own letter index item using `renderCustomIndexLetter`. 

This to be released in a new version shortly. Thanks!
