### ISSUE TITLE
Date Not Updating in runtime

### ISSUE THREAD

**Issue by dhairyasenjaliya** [Kieran-McIntyre/react-native-section-alphabet-list#14]
Expected Behavior
If we change data source at run time Section list should dynamically updated

Actual Behavior
Currentlyif we change data source section list is not getting current data

**Comment by Kieran-McIntyre** [comment]
> Expected Behavior
> If we change data source at run time Section list should dynamically updated
> 
> Actual Behavior
> Currentlyif we change data source section list is not getting current data

Hey @dhairyasenjaliya, thanks for raising this. I can see that you've asked for support on a different issue. Did the suggestion noted [here](https://github.com/Kieran-McIntyre/react-native-section-alphabet-list/issues/12#issuecomment-820495630) resolve your problem?

**Comment by dhairyasenjaliya** [comment]
hello @Kieran-McIntyre not that didn't help i have debugged issue thing is like data source object is getting updated but the section list keeps the old data while vertical alphabet changes in real time maybe issue in the section list also tried to add extra props and keys as well

**Comment by Thiousi** [comment]
@dhairyasenjaliya could you show the piece of code you are using to define what you are passing in the `data` prop?
If you want the data to update, you should be using `useState()` hook or `this.state` in your props depending on whether you are calling AlphabetList within a function or component.

**Comment by dhairyasenjaliya** [comment]
hello find the workout if we need to update data then we just need to clear allData and then set again
