### ISSUE TITLE
Ability to hide scroll bar

### ISSUE THREAD

**Issue by HumayounBaig** [Kieran-McIntyre/react-native-section-alphabet-list#3]
Hello, great repo there,
I was going through docs but was unable to find ability to hide scroll bar as it interferes with the alphabets. Is there any way to do so?

![image](https://user-images.githubusercontent.com/32910163/89802970-a675f580-db4b-11ea-94df-dedde58e4cf8.png)

**Comment by kfiri** [comment]
You can do that by adding the prop `showsHorizontalScrollIndicator={false}`.
The props given to `AlphabetList` are passed down to the `SectionList` used for the list.
You can see more optional props in [`the SectionList Docs`](https://reactnative.dev/docs/sectionlist#props) and in [`the ScrollView Docs`](https://reactnative.dev/docs/scrollview#props).
The docs for the showsHorizontalScrollIndicator prop is under ScrollView.

**Comment by kfiri** [comment]
However, I don't think that the author of this package inherit from props interface of SectionList, so you might run into some issues if you are using typescript.
It doesn't look like this repo is being maintained as well... :\

**Comment by HumayounBaig** [comment]
@kfiri yeah i think that's the issue exactly it is not accepting srollview props.
But is there any other module you know of that does perform same functionality

**Comment by kfiri** [comment]
Well, you can bypass the typescript error by defining the props as `any`, but that's hacky.
I just chose to implement my component from scratch using `SectionList` instead of using this package

**Comment by HumayounBaig** [comment]
Can you share your implementation please.
As i am unable to find a similar package with alphabets to jump to on side

**Comment by kfiri** [comment]
I'm currently still working on the implementation, I wonder how should the index list look like when the index items overflow,
Here is what I have right now:
![ISblNKlcRS](https://user-images.githubusercontent.com/31252902/91843771-f9c8f880-ec5e-11ea-89d3-c0251b2c942e.gif)

Maybe I'll upload it as a package of it's own instead of having it only in the app what I'm working on

**Comment by kfiri** [comment]
I began to work on this project, it is still in WIP condition (no docs yet), but you can browse the code :)
https://github.com/kfiri/indexed-section-list

**Comment by kfiri** [comment]
@HumayounBaig

**Comment by Kieran-McIntyre** [comment]
> Hello, great repo there,
> I was going through docs but was unable to find ability to hide scroll bar as it interferes with the alphabets. Is there any way to do so?
> 
> ![image](https://user-images.githubusercontent.com/32910163/89802970-a675f580-db4b-11ea-94df-dedde58e4cf8.png)

Hey @HumayounBaig, the component has now been updated to inherit from `SectionList` props.  Just add the prop `showsVerticalScrollIndicator={false}` and this should hide the scrollbar for you.

**Comment by HumayounBaig** [comment]
That's great, thanks for letting me know
