### ISSUE TITLE
Support for Turkish Characters

### ISSUE THREAD

**Issue by Canser** [Kieran-McIntyre/react-native-section-alphabet-list#6]
Hello.

The names that start with "Ü", "Ş", "Ğ", "Ç", "Ö", "İ" are grouped under "#" character.

**Comment by Kieran-McIntyre** [comment]
Hey @Canser, the default `index` prop is an array containing the characters of the English alphabet. If you want to support the Turkish alphabet, you can pass in a custom `index`. For example:

```javascript

// custom index with turkish characters
const myCustomIndex = [
    "a",
    "b",
    "c",
    "ç",
    "d",
    "e",
    "f",
    "g",
    "ğ"
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "ö",
    "p",
    "q",
    "r",
    "s",
    "ş",
    "t",
    "u",
    "ü",
    "v",
    "w",
    "x",
    "y",
    "z",
]

const MyComponent = () => {
     return  (
         <AlphabetList
              index={myCustomIndex}
              ...
         />
     )
}
```
Please let me know if this works for you. You can read more about the `index` prop [here](https://github.com/Kieran-McIntyre/react-native-section-alphabet-list#custom-index). Thanks!

**Comment by Canser** [comment]
@Kieran-McIntyre Yes, it works. Thanks!

**Comment by Thiousi** [comment]
Hello @Canser ,
Your reply helped a lot. Is there any chance we could regroup two letters under the same section?
I've been trying with no luck. 
In the example above, could we regroup "g" and "ğ" ?

Thanks !

**Comment by Kieran-McIntyre** [comment]
> Hello @Canser ,
> Your reply helped a lot. Is there any chance we could regroup two letters under the same section?
> I've been trying with no luck.
> In the example above, could we regroup "g" and "ğ" ?
> 
> Thanks !

Hey @Thiousi,

Unfortunately, this is currently not possible. But if you'd like to raise a new issue, we can start a discussion about how this could be implemented. For example, maybe we could do something like

```javascript
const myCustomIndex = [
    "a",
    "b",
    "c",
    "ç",
    "d",
    "e",
    "f",
    ["g", "ğ"],
    "h",
    "i",
    ...
]
```

Thanks!
